### ISSUE TITLE
Error in pic numbering

### ISSUE THREAD

**Issue by chizoba** [srbcheema1/puzzle4x4#24]
@srbcheema1 there is a maximum of pic11, and a maximum of slice 15 pic X. how come there is no pic12, pic13, pic14, and pic15??

**Comment by srbcheema1** [comment]
we can add more pics any number of pics can be added ...
there may be pic20 also ...
but slices MUST be 16 per pic ...
i.e. slice 0 pic X   to   slice 15 pic X

**Comment by chizoba** [comment]
My complain is that there is NO main picture for some slices available. i.e. from pic 12 to pic 15

**Comment by srbcheema1** [comment]
@chizoba 
there are no slices for pic 12 to 15 i think 
last pic is pic11
check that out again if there is any `slice 0 pic 12`
please send its link in comment .
i cant see any maybe i be missing something .

**Comment by chizoba** [comment]
oh! i see. i misinterpreted the slice X and pic X format. Thought it was the other way around. Sorry about that.
