### ISSUE TITLE
update images used in the game

### ISSUE THREAD

**Issue by srbcheema1** [srbcheema1/puzzle4x4#9]
contributers for hactoberfest are welcome to update the images in the game 
just be careful with the dimentions of new images you add .
any kind of contibution is accepted

**Comment by lincolncosta** [comment]
how many images do you need? and what is the expected dimensions? i can help you with that

**Comment by AliaksandrY** [comment]
Added pic5 https://github.com/srbcheema1/puzzle4x4/pull/12

**Comment by srbcheema1** [comment]
@tekpixo you may replace any picture with a better one .
keep the dimensions of new picture same as the picture being replaced

**Comment by maitreyav** [comment]
I'd like to work on it.

**Comment by srbcheema1** [comment]
there are 2 type of pictures required for the puzzle
 1. the main picture . 
  .. that needs to be 960 x 960 pixel (resize or crop to get  best square pic )
 2. 16 cuttings of that main picture 
  .. they must be 120 x 120 pixel

**Comment by srbcheema1** [comment]
@maitreyav 
go for it :)

**Comment by srbcheema1** [comment]
PLEASE NOTE 
name of main pic mustbe picX.jpg
name of slice must be slice X pic X .jpg
here X is the number 4 , 5 . 6 so on ....
...
also verify the pic number they are working on .
that number must not be  used by some other pic otherwise there will be conflict while merging
....
also every slice must be uniquely visible
no two slices must be identical in appearance

**Comment by AliaksandrY** [comment]
Added pic 7 https://github.com/srbcheema1/puzzle4x4/pull/18

**Comment by talitahalboth** [comment]
Added pic 8 :) (and it's a drawing by my i'm so proud of it)

**Comment by srbcheema1** [comment]
thanks @OMGHaveFun @tekpixo 
thanks for your contributions :)
happy coding :smile:

**Comment by chizoba** [comment]
@srbcheema1 can i still add more?

**Comment by srbcheema1** [comment]
@chizoba  go for it
